spring:
  application:
    name: skin-auth
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

mybatis:
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 19081
  address: 0.0.0.0
